version: '3'

services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
  aredn-manager:
    image: ghcr.io/usa-reddragon/aredn-cloud-tunnel:v0.0.1
    restart: unless-stopped
    privileged: true
    environment:
      - PG_HOST=postgres
      - PG_PASSWORD=password
      - SESSION_SECRET=changeme
      - PASSWORD_SALT=alsochangeme
      - CORS_HOSTS=http://localhost,http://127.0.0.1
      - INIT_ADMIN_USER_PASSWORD=changeme
      - SERVER_NAME=cloud-tunnel
      - SERVER_LON=-83
      - SERVER_LAT=39.96
      - SERVER_GRIDSQUARE=KA97xa
      - DEBUG=1
    ports:
      - 5525:5525
      - 80:80
volumes:
  postgres:
