version: '3'

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  aredn-manager:
    build: .
    restart: unless-stopped
    privileged: true
    environment:
      - PG_HOST=postgres
      - PG_PASSWORD=password
      - SESSION_SECRET=changeme
      - PASSWORD_SALT=alsochangeme
      - CORS_HOSTS=http://localhost:81,http://127.0.0.1:81
      - INIT_ADMIN_USER_PASSWORD=changeme
      - SERVER_NAME=cloud-tunnel
      - SERVER_LON=-83
      - SERVER_LAT=39.96
      - SERVER_GRIDSQUARE=KA97xa
      - MAP_CONFIG={"name":"AREDN","mapSettings":{"zoom":"10","mapCenter":{"node":"CLOUD-TUNNEL","lat":"39.96","lon":"-83"},"servers":[{"test":"https://c.tile.openstreetmap.org/10/162/395.png","url":"https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"}]},"contactInfo":{"callsign":"opcallsign","name":"OpName","email":"opEmail"},"nodesFilter":".*","offline":false}
      - DEBUG=1
    ports:
      - 3333:3333
      - 81:81
volumes:
  postgres:
